export const MESSAGE_TYPES = {
  PATH_STATUS: 'PATH_STATUS',
  REGULAR_FRAME_READY: 'REGULAR_FRAME_READY',
  DEPTH_FRAME_READY: 'DEPTH_FRAME_READY',
  DEPTH_MATRIX_READY: 'DEPTH_MATRIX_READY',
  REGULAR_FRAME_CAPTURED: 'REGULAR_FRAME_CAPTURED',
  DEPTH_FRAME_CAPTURED: 'DEPTH_FRAME_CAPTURED',
  COVIZ_MATRIX_INITIALIZED: 'COVIZ_MATRIX_INITIALIZED',
  COVIZ_MATRIX_READY: 'COVIZ_MATRIX_READY',
  COVIZ_MATRIX_CAPTURED: 'COVIZ_MATRIX_CAPTURED',
  PROCESSING_COMPLETE: 'PROCESSING_COMPLETE',
  COVIZ_MATRIX_PROGRESS: 'COVIZ_MATRIX_PROGRESS',
};

export const PATH_STATUS = {
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  DISCARDED: 'discarded',
};
