export const MESSAGE_TYPES = {
  PATH_STATUS: 'PATH_STATUS',
  REGULAR_FRAME_READY: 'REGULAR_FRAME_READY',
  DEPTH_FRAME_READY: 'DEPTH_FRAME_READY',
  DEPTH_MATRIX_READY: 'DEPTH_MATRIX_READY',
  REGULAR_FRAME_CAPTURED: 'REGULAR_FRAME_CAPTURED',
  DEPTH_FRAME_CAPTURED: 'DEPTH_FRAME_CAPTURED',
  PROCESSING_COMPLETE: 'PROCESSING_COMPLETE',
};

export const PATH_STATUS = {
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  DISCARDED: 'discarded',
};
